- hosts: all
  vars_files:
    - varsInstallApiEnv.yml
  tasks:

    - name: Add known_hosts Nodo1
      become: yes
      become_user: ansible
      shell: "ssh-keyscan -H {{ip_nodo1}} >> ~/.ssh/known_hosts"

    - name: Add known_hosts Nodo2
      become: yes
      become_user: ansible
      shell: "ssh-keyscan -H  {{ip_nodo2}} >> ~/.ssh/known_hosts"

    - name: Add known_hosts Nodo3
      become: yes
      become_user: ansible
      shell: "ssh-keyscan -H  {{ip_nodo3}} >> ~/.ssh/known_hosts"      
