- hosts: nodo3
  vars_files:
    - varsInstallApiEnv.yml
  tasks:

    - name: Create server-zuul service
      become: yes
      become_user: root
      file:
        path: "/etc/systemd/system/server-zuul.service"
        state: touch

    - name: Update server-zuul service
      become: yes
      become_user: root
      blockinfile:
        path: "/etc/systemd/system/server-zuul.service"
        block: |
          [Unit]
          Description=Manage server zuul service

          [Service]
          WorkingDirectory=/u01/server-zuul
          ExecStart=java -jar -DPROFILE=serverzuulambientecele -DEUREKA_SERVER=http://localhost:5601/eureka /u01/server-zuul/server-zuul-0.0.1.jar
          User=jvmapps
          Type=simple
          Restart=on-failure
          RestartSec=10

    - name: Create server-zuul directory
      become: yes
      become_user: root
      file:
        path: "/u01/server-zuul"
        state: directory

    - name: Copy server-zuul
      become: yes
      become_user: root
      ansible.builtin.copy:
        src: "{{ path_base_servers }}/{{ path_server_zuul }}/server-zuul-0.0.1.jar"
        dest: "/u01/server-zuul"
        owner: jvmapps
        group: appmgr

    - name: Change server-zuul path permission
      become: yes
      file:
        path: "/u01/server-zuul"
        recurse: yes
        owner: jvmapps
        group: appmgr        

    - name: apt reload deamon
      become: yes
      become_user: root
      shell: "systemctl daemon-reload"

    - name: Start /u01/server-zuul service
      become: yes
      become_user: root
      ansible.builtin.systemd:
        state: started
        name: server-zuul.service
        enabled: true
