- hosts: nodo4
  vars_files:
    - varsInstallApiEnv.yml
  tasks:

    - name: Add usldap user
      become: yes
      become_user: root
      user:
        name: usldap
        create_home: yes
        comment: User Keycloak
        password: "{{  passwd_usldap_os | password_hash('sha512') }}"

    - name: Create keycloak directory
      become: yes
      become_user: root
      file:
        path: "{{path_openldap}}"
        state: directory

    - name: Change openldap base permission
      become: yes
      become_user: root
      file:
        path: "{{path_openldap}}"
        recurse: yes
        owner: usldap
        group: usldap

   - name: Install slapd
      become: yes
      become_user: root
      ansible.builtin.apt:
        name: slapd
        state: present

   - name: Install ldap-utils
      become: yes
      become_user: root
      ansible.builtin.apt:
        name: ldap-utils
        state: present      
